version: '3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - server/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: web-server
    ports:
      - "3000:3000"
    env_file:
      - server/.env.dev
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules:
