# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json into the root directory of your container
COPY package*.json pnpm-lock.yaml ./

# Install your dependencies
RUN npm install -g pnpm
RUN pnpm install

# Install nodemon for hot-reloading
RUN npm install -g nodemon

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Make port 3000 available to the outside world
EXPOSE 3000

# Define the command to run your app using CMD which defines your runtime
CMD [ "nodemon", "server.mjs" ]